function T = loadScenarios(csvFile, varargin)
%LOADSCENARIOS Read and validate the canonical MATLAB scenario table.
%
%   T = LOADSCENARIOS(csvFile) reads the canonical adapter CSV
%   (data/canonical/matlab_scenarios.csv, auto-generated by the Python
%   fcf_m2.matlab_adapter) and returns a validated MATLAB table.
%
%   T = LOADSCENARIOS(csvFile, Name, Value, ...) filters the table:
%       'SiteId'      - string/char or string array of site_id values
%                       (join key; NEVER filter on site_name per the
%                       data-contract consumer rules).
%       'HorizonYear' - numeric scalar/vector of horizon years. Horizons
%                       are read FROM THE DATA; no year list is
%                       hard-coded anywhere in this repository (ML-06).
%       'Case'        - string/char or string array among the case labels
%                       present in the data (e.g. "baseline","base",
%                       "high","stress_combined").
%       'ScenarioId'  - exact scenario_id value(s).
%
%   Validation performed (fail-closed, ML-01 / ML-04):
%     * All required columns must be present, else a hard error.
%     * capacity_basis must be present and non-empty on EVERY selected
%       row, else a hard error - capacity provenance can never be
%       silently absent.
%     * Numeric sanity: ports >= 0, charger_power_kW > 0,
%       arrival_end_hr > arrival_start_hr, dwell_hr > 0,
%       sessions_per_day >= 0, energy_per_session_kWh >= 0.
%
%   Units: kW, kWh, hours (see DATA_DICTIONARY.md).
%
%   Part of Milestone 2 V3 implementation (items ML-01, ML-06).
%   See README.md for provenance and regeneration instructions.

    % ---------------------------------------------------------------
    % Parse arguments
    % ---------------------------------------------------------------
    p = inputParser;
    p.FunctionName = "loadScenarios";
    addParameter(p, "SiteId", string.empty, @(v) isstring(string(v)));
    addParameter(p, "HorizonYear", [], @(v) isnumeric(v));
    addParameter(p, "Case", string.empty, @(v) isstring(string(v)));
    addParameter(p, "ScenarioId", string.empty, @(v) isstring(string(v)));
    parse(p, varargin{:});
    filt = p.Results;

    % ---------------------------------------------------------------
    % Read the CSV
    % ---------------------------------------------------------------
    if ~isfile(csvFile)
        error("loadScenarios:fileNotFound", ...
            "Canonical scenario CSV not found: %s\n" + ...
            "Expected data/canonical/matlab_scenarios.csv (auto-generated " + ...
            "by the Python adapter; see README.md 'Regeneration').", csvFile);
    end

    % "case" is a MATLAB keyword, so the CSV column "case" is imported
    % with its name preserved and then renamed to "case_label" for safe
    % dot access throughout this codebase (documented in DATA_DICTIONARY.md).
    % The delimiter, the header line and the first data line are all SPECIFIED, not
    % detected. This file is written by the Python producer as comma-separated with a
    % header on line 1; there is nothing to guess, and guessing was actively wrong.
    %
    % The first real MathWorks run exposed it. detectImportOptions inspected a row whose
    % free-text columns carry more spaces than the row has commas and concluded the
    % delimiter was whitespace: it reported 51 variables instead of 22, decided the header
    % was on line 2, and returned 119 rows instead of 120. Every required column was then
    % "missing", which is a confusing way to be told the file was never parsed as a CSV.
    %
    % The canonical file is exposed to the same misdetection - 35 spaces against 21 commas
    % on its first data row - so this is a latent defect in the loader, not a property of
    % any one input. It could only ever have surfaced by executing the code.
    opts = detectImportOptions(csvFile, ...
        "Delimiter", ",", ...
        "VariableNamesLine", 1, ...
        "DataLines", [2 Inf], ...
        "TextType", "string", ...
        "VariableNamingRule", "preserve");

    stringCols = ["scenario_id", "site_id", "site_name", "case", ...
                  "capacity_basis", "capacity_source", ...
                  "managed_charging_policy", "electrical_risk_level", ...
                  "source_note"];
    presentStringCols = intersect(stringCols, string(opts.VariableNames));
    if ~isempty(presentStringCols)
        opts = setvartype(opts, presentStringCols, "string");
    end

    T = readtable(csvFile, opts);

    % Rename the keyword-clashing column for safe dot access.
    if ismember("case", string(T.Properties.VariableNames))
        T = renamevars(T, "case", "case_label");
    end

    % ---------------------------------------------------------------
    % Column validation (hard errors, never warnings)
    % ---------------------------------------------------------------
    requiredCols = ["scenario_id", "site_id", "site_name", ...
        "horizon_year", "case_label", "ports", "charger_power_kW", ...
        "spare_capacity_kW", "service_capacity_kW", "capacity_basis", ...
        "capacity_source", "base_load_mean_kW", "base_load_peak_kW", ...
        "arrival_start_hr", "arrival_end_hr", "dwell_hr", ...
        "sessions_per_day", "energy_per_session_kWh", ...
        "managed_charging_policy"];

    missingCols = setdiff(requiredCols, string(T.Properties.VariableNames));
    if ~isempty(missingCols)
        error("loadScenarios:missingColumns", ...
            "Canonical CSV %s is missing required column(s): %s. " + ...
            "Do not hand-edit the CSV; regenerate it from the Python " + ...
            "adapter (fcf_m2.matlab_adapter).", ...
            csvFile, strjoin(missingCols, ", "));
    end

    % capacity_basis must be non-empty everywhere (ML-04 fail-closed).
    basis = strtrim(string(T.capacity_basis));
    badBasis = ismissing(basis) | basis == "";
    if any(badBasis)
        firstBad = find(badBasis, 1);
        error("loadScenarios:missingCapacityBasis", ...
            "Row %d (scenario_id=%s) has an empty capacity_basis. " + ...
            "Every scenario row MUST declare capacity provenance " + ...
            "(see capacityGuard.m for the controlled vocabulary). " + ...
            "Refusing to load.", firstBad, string(T.scenario_id(firstBad)));
    end

    % ---------------------------------------------------------------
    % Numeric sanity checks
    % ---------------------------------------------------------------
    localAssertNumeric(T, "ports", @(v) v >= 0, "ports must be >= 0");
    localAssertNumeric(T, "charger_power_kW", @(v) v > 0, ...
        "charger_power_kW must be > 0");
    localAssertNumeric(T, "dwell_hr", @(v) v > 0, "dwell_hr must be > 0");
    localAssertNumeric(T, "sessions_per_day", @(v) v >= 0, ...
        "sessions_per_day must be >= 0");
    localAssertNumeric(T, "energy_per_session_kWh", @(v) v >= 0, ...
        "energy_per_session_kWh must be >= 0");

    badWindow = T.arrival_end_hr <= T.arrival_start_hr;
    if any(badWindow)
        firstBad = find(badWindow, 1);
        error("loadScenarios:badArrivalWindow", ...
            "Row %d (scenario_id=%s): arrival_end_hr (%.2f) must be " + ...
            "strictly greater than arrival_start_hr (%.2f).", ...
            firstBad, string(T.scenario_id(firstBad)), ...
            T.arrival_end_hr(firstBad), T.arrival_start_hr(firstBad));
    end

    % ---------------------------------------------------------------
    % Filtering (site_id join only; horizons come from the data)
    % ---------------------------------------------------------------
    keep = true(height(T), 1);

    if ~isempty(filt.SiteId)
        keep = keep & ismember(string(T.site_id), string(filt.SiteId));
    end
    if ~isempty(filt.HorizonYear)
        keep = keep & ismember(T.horizon_year, filt.HorizonYear);
    end
    if ~isempty(filt.Case)
        keep = keep & ismember(string(T.case_label), string(filt.Case));
    end
    if ~isempty(filt.ScenarioId)
        keep = keep & ismember(string(T.scenario_id), string(filt.ScenarioId));
    end

    T = T(keep, :);

    if height(T) == 0
        error("loadScenarios:noMatch", ...
            "No scenario rows match the requested filter. Available " + ...
            "horizons and cases are read from the data; check your " + ...
            "SiteId / HorizonYear / Case values against the CSV.");
    end

    % Attach provenance metadata to the table for downstream consumers.
    T.Properties.Description = "Canonical MATLAB scenario table (auto-generated adapter)";
    T.Properties.UserData = struct( ...
        "source_csv", string(csvFile), ...
        "loaded_utc", string(datetime("now", "TimeZone", "UTC", ...
            "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
        "horizons_in_data", unique(T.horizon_year(:)).', ...
        "cases_in_data", unique(string(T.case_label(:))).');
end

function localAssertNumeric(T, colName, predicate, message)
%LOCALASSERTNUMERIC Hard-fails when any non-NaN value violates predicate.
    v = T.(colName);
    if ~isnumeric(v)
        error("loadScenarios:columnType", ...
            "Column %s must be numeric; got %s.", colName, class(v));
    end
    ok = isnan(v) | predicate(v);
    if ~all(ok)
        firstBad = find(~ok, 1);
        error("loadScenarios:badValue", ...
            "Row %d (scenario_id=%s), column %s: %s (got %.4g).", ...
            firstBad, string(T.scenario_id(firstBad)), colName, ...
            message, v(firstBad));
    end
end
