function csvFile = resolveScenarioCsv()
%RESOLVESCENARIOCSV Locate the scenario table, wherever this copy of the model lives.
%
%   These sources run in two places: the private repository, where the canonical
%   adapter CSV is generated by the Python producer, and the PUBLIC CI harness,
%   which carries a synthetic fixture instead and must never carry the real one.
%
%   The first real MathWorks run failed here. The tests and the batch runner both
%   hard-coded data/canonical/matlab_scenarios.csv, so in the harness 14 tests
%   errored with "Canonical scenario CSV not found" before exercising any model
%   logic. Hard-coding the path made the sources non-portable between the two trees,
%   and the alternative -- editing the harness copy -- is exactly the divergence the
%   one-directional sync exists to prevent.
%
%   Search order, first hit wins:
%     1. $FCF_SCENARIO_CSV, if set (explicit override, for a caller with its own file)
%     2. <repo>/data/canonical/matlab_scenarios.csv        (private: real, generated)
%     3. <repo>/data/harness_scenarios_synthetic.csv       (public harness: synthetic)
%
%   Order matters: the real file wins when both exist, so the private repository
%   never silently tests against synthetic data.

    thisDir = fileparts(mfilename("fullpath"));
    repoRoot = fileparts(thisDir);

    override = getenv("FCF_SCENARIO_CSV");
    if ~isempty(override) && isfile(override)
        csvFile = override;
        return;
    end

    candidates = { ...
        fullfile(repoRoot, "data", "canonical", "matlab_scenarios.csv"), ...
        fullfile(repoRoot, "data", "harness_scenarios_synthetic.csv")};

    for k = 1:numel(candidates)
        if isfile(candidates{k})
            csvFile = candidates{k};
            return;
        end
    end

    error("resolveScenarioCsv:notFound", ...
        "No scenario CSV found. Looked for $FCF_SCENARIO_CSV, then %s, then %s. " + ...
        "In the private repository, regenerate the canonical CSV with the Python " + ...
        "adapter (make run-v3). In the harness, the synthetic fixture is synced " + ...
        "from the private repository - do not hand-create it here.", ...
        candidates{1}, candidates{2});
end
